app:
    app_name: "lrkv"
    app_logging_level: "INFO"

    ROOT_DIR: "lrkv"
    DATA_DIR: "data"

    EXECUTION_PATH: "build/db_runner"
    # EXECUTION_PATH: "build/sim_runner"
    DATABASE_PATH: "/tmp"
    # DATABASE_PATH: "/dev/shm"
    KEY_FILE_PATH: "data/keys.data"

lsm_tree_config: 
    N: 10000000
    phi: 1
    s: 0.0000002        # Average range query selectivity
    B: 4            # Number of entries that fit in a disk page
    E: 8192         # Size of data entries in bits
    M: 8589934592   # Total memory budget of 1 GiB
    is_leveling_policy: False  # Leveling or Tiering policy

jobs:
    job_list:
        - "run_experiments"

experiments:
    expt_list:
        - "LevelCost"

lr_model:
    level_lr_cache_model: "model/level_lr_sim_cache_model.pkl"
    level_lr_cost_model: "model/level_lr_sim_cost_model.pkl"
    tier_lr_cache_model: "model/tier_lr_sim_cache_model.pkl"
    tier_lr_cost_model: "model/tier_lr_sim_cost_model.pkl"

xgb_model:
    level_xgb_cost_model: "model/level_cost_xgb_uni_sim.pkl"
    tier_xgb_cost_model: "model/tier_cost_xgb_uni_sim.pkl"

samples_path:
    lr_level_ckpt: "raw_data/samples_sim_lr_level_uniform_ckpt.csv"
    lr_level_final: "raw_data/samples_sim_lr_level_uniform_final.csv"
    lr_tier_ckpt: "raw_data/samples_sim_lr_tier_uniform_ckpt.csv"
    lr_tier_final: "raw_data/samples_sim_lr_tier_uniform_final.csv"
    xgb_level_ckpt: "raw_data/samples_sim_xgb_level_uniform_ckpt.csv"
    xgb_level_final: "raw_data/samples_sim_xgb_level_uniform_final.csv"
    xgb_tier_ckpt: "raw_data/samples_sim_xgb_tier_uniform_ckpt.csv"
    xgb_tier_final: "raw_data/samples_sim_xgb_tier_uniform_final.csv"

optimizer_path:
    ckpt: "optimizer_data/optimizer_sim_uniform_ckpt.csv"
    final: "optimizer_data/optimizer_sim_uniform_final.csv"